netmap: addsupport subnetwork ID to `PlacementPolicy`
nspcc-dev/neofs-api-go pull request #358
Opened 2021-11-17 06:38 UTC by fyrchik

Related #355 .

2021-11-17 08:00 UTC, cthulhu-rider requested changes

2021-11-17 08:00 UTC, cthulhu-rider commented on v2/refs/types.go
> +func (s *SubnetID) SetID(id uint32) {
```suggestion
func (s *SubnetID) SetValue(id uint32) {
```

Pretty strange to set ID of the ID. Same for getter.

2021-11-17 12:30 UTC, alexvanin commented
Try to recompile files with new `prepare.sh` script after #357

2021-11-17 15:26 UTC, cthulhu-rider approved these changes
Pls use `protoc-gen-go >=v3.18.0` to compile proto files.

2021-11-18 12:03 UTC, cthulhu-rider approved these changes

2021-11-18 12:04 UTC, merged